<a href="https://colab.research.google.com/github/NevaehF/CSC115/blob/main/Week2_Assignment_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.

In [3]:
# Following along
import numpy as np

arr= np.array([1,2, 3, 4,5, 6])
reshaped=arr.reshape(2, -2) #2 rows, infer columns(will be 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix

In [4]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0] ])  # 3x3

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6] ])  # 3x2

C = A @ B  # or np.matmul(A, B)
print(C)

[[22 28]
 [23 28]
 [23 34]]


Write a NumPy program to find the most frequent value and the number of times it occured in the array


[

    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]  
 ]

In [5]:
#The notes and instruction given are truly very helpful. I like that I am able to understand what things do as a whole and individually

import numpy as np

arr = np.array([
    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9] ])

values, counts = np.unique(arr, return_counts=True)
max_idx = counts.argmax()
mode_value = values[max_idx]
mode_count = counts[max_idx]

print("Most frequent value:", mode_value)
print("Occurrences:", mode_count)

Most frequent value: 2
Occurrences: 9


Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.

[  [ 1.  2. nan  4.  5.],

 [ 6. nan  8.  9. 10.],

 [11. 12. 13. nan 15.],

 [16. 17. nan 19. 20.],

 [nan 22. 23. 24. 25.]  ]

In [6]:
import numpy as np

data = np.array([
    [ 1.,  2.,  np.nan,  4.,  5.],
    [ 6.,  np.nan,  8.,  9., 10.],
    [11., 12., 13.,  np.nan, 15.],
    [16., 17.,  np.nan, 19., 20.],
    [ np.nan, 22., 23., 24., 25.] ], dtype=float)

col_means = np.nanmean(data, axis=0)         # mean per column, ignoring NaNs
nan_rows, nan_cols = np.where(np.isnan(data)) # These are the coordinates of NaNs
data[nan_rows, nan_cols] = col_means[nan_cols]  # fill with column means
print(data)

[[ 1.          2.         14.66666667  4.          5.        ]
 [ 6.         13.25        8.          9.         10.        ]
 [11.         12.         13.         14.         15.        ]
 [16.         17.         14.66666667 19.         20.        ]
 [ 8.5        22.         23.         24.         25.        ]]


Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.

np.array([

    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
]

In [7]:
import numpy as np

data = np.array([
    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550) ], dtype=object)

# We need to extract the date column and convert to datetime64
dates = data[:, 0].astype('datetime64[D]')

# Next we need to convert to month precision and get month number (1–12)
months = (dates.astype('datetime64[M]').astype(int) % 12) + 1

# Then append as a new column (object dtype to mix types)
result = np.column_stack((data, months))
print(result)

# Each row then becomes: (date_str, val1, val2, month_number)

[['2024-01-15' 10 100 1]
 ['2024-02-28' 15 150 2]
 ['2024-03-10' 20 200 3]
 ['2024-04-22' 25 250 4]
 ['2024-05-05' 30 300 5]
 ['2024-06-18' 35 350 6]
 ['2024-07-30' 40 400 7]
 ['2024-08-12' 45 450 8]
 ['2024-09-25' 50 500 9]
 ['2024-10-07' 55 550 10]]
